import {
  faCoins,
  faGem,
  faHome,
  faUserGroup,
  faTimes,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faStar,
  faCheck,
  faQuestion,
  faClock,
  faInfoCircle,
  faArrowRight,
  faAngleDoubleUp,
  faBolt,
  faRocket,
  faHammer,
  faHandPointer,
  faBatteryFull,
  faBatteryHalf,
  faSearch,
  faSort,
  faPlus,
  faFilter,
  faGlobe,
  faGift,
  faCalendar,
  faListCheck,
  faBookOpen,
  faPlay,
  faLevelUpAlt,
  faBell,
} from "@fortawesome/free-solid-svg-icons"

// Import brand icons
import {
  faYoutube,
  faTwitter,
  faTelegram,
  faInstagram,
  faFacebook,
  faLinkedin,
} from "@fortawesome/free-brands-svg-icons"

export const icons = {
  // General icons
  coins: faCoins,
  swords: faGem, // Using faGem as sword alternative
  home: faHome,
  userGroup: faUserGroup,
  times: faTimes,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  star: faStar,
  check: faCheck,
  question: faQuestion,
  clock: faClock,
  infoCircle: faInfoCircle,
  arrowRight: faArrowRight,
  angleDoubleUp: faAngleDoubleUp,
  bolt: faBolt,
  rocket: faRocket,
  pickaxe: faHammer, // Using faHammer as pickaxe alternative
  handPointer: faHandPointer,
  batteryFull: faBatteryFull,
  batteryHalf: faBatteryHalf,
  search: faSearch,
  sort: faSort,
  plus: faPlus,
  filter: faFilter,
  globe: faGlobe,
  gift: faGift,
  calendar: faCalendar,
  listCheck: faListCheck,
  bookOpen: faBookOpen,
  play: faPlay,
  levelUp: faLevelUpAlt,
  bell: faBell,
  
  // Brand icons
  youtube: faYoutube,
  twitter: faTwitter,
  telegram: faTelegram,
  instagram: faInstagram,
  facebook: faFacebook,
  linkedin: faLinkedin,
}