import {
  faCoins,
  faGem,
  faHome,
  faUserGroup,
  faTimes,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faStar,
  faCheck,
  faQuestion,
  faClock,
  faInfoCircle,
  faArrowRight,
  faAngleDoubleUp,
  faBolt,
  faRocket,
  faHammer,
  faHandPointer,
  faBatteryFull,
  faBatteryHalf,
  faSearch,
  faSort,
  faPlus,
  faFilter,
} from "@fortawesome/free-solid-svg-icons"

export const icons = {
  coins: faCoins,
  swords: faGem, // Replace faSwords with faGem but keep the same key
  home: faHome,
  userGroup: faUserGroup,
  times: faTimes,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  star: faStar,
  check: faCheck,
  question: faQuestion,
  clock: faClock,
  infoCircle: faInfoCircle,
  arrowRight: faArrowRight,
  angleDoubleUp: faAngleDoubleUp,
  bolt: faBolt,
  rocket: faRocket,
  pickaxe: faHammer, // Changed from faPickaxe to faHammer
  handPointer: faHandPointer,
  batteryFull: faBatteryFull,
  batteryHalf: faBatteryHalf,
  search: faSearch,
  sort: faSort,
  plus: faPlus,
  filter: faFilter,
}
