import {
  faCoins,
  faSwords,
  faHome,
  faUserGroup,
  faTimes,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faStar,
  faCheck,
  faQuestion,
  faClock,
  faInfoCircle,
  faArrowRight,
  faAngleDoubleUp,
  faBolt,
  faRocket,
  faCopy,
} from "@fortawesome/free-solid-svg-icons"

export const icons = {
  coins: faCoins,
  swords: faSwords,
  home: faHome,
  userGroup: faUserGroup,
  times: faTimes,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  star: faStar,
  check: faCheck,
  question: faQuestion,
  clock: faClock,
  infoCircle: faInfoCircle,
  arrowRight: faArrowRight,
  angleDoubleUp: faAngleDoubleUp,
  bolt: faBolt,
  rocket: faRocket,
  copy: faCopy,
}
