import {
  faUser,
  faCoins,
  faXmark,
  faStar,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faCheck,
  faHourglassStart,
  faAngleDoubleUp,
  faArrowRight,
  faBolt,
  faRocket,
  faClock,
  faInfoCircle,
  faQuestion,
  faGift,
  faExternalLinkAlt,
  faCopy,
  faHome,
  faUserGroup,
  // Removed faSwords completely
  faHeart,
  faSignal,
  faGamepad,
  faArrowUp,
  faFire,
  faPlus,
  faTrophy,
} from "@fortawesome/free-solid-svg-icons"

// Create the icons object
export const icons = {
  coins: faCoins,
  times: faXmark,
  star: faStar,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  check: faCheck,
  hourglassStart: faHourglassStart,
  angleDoubleUp: faAngleDoubleUp,
  arrowRight: faArrowRight,
  bolt: faBolt,
  rocket: faRocket,
  clock: faClock,
  infoCircle: faInfoCircle,
  question: faQuestion,
  gift: faGift,
  externalLinkAlt: faExternalLinkAlt,
  copy: faCopy,
  home: faHome,
  userGroup: faUserGroup,
  // Using faHammer as a replacement for swords
  swords: faUser, // Temporarily using faUser instead of swords
  heart: faHeart,
  signal: faSignal,
  gamepad: faGamepad,
  arrowUp: faArrowUp,
  fire: faFire,
  plus: faPlus,
  trophy: faTrophy,
  user: faUser,
}

// Export the icons object
export default icons
